server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location ~* \.(glb|bin|png|jpg|jpeg|webp|js|css|woff2)$ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800, immutable";
        try_files $uri =404;
    }

    location /island/ {
        try_files $uri $uri/ /island/index.html;
    }
}
