const LABELS: Record<string, string> = {
  "session.start": "Зашёл на остров",
  "session.heartbeat": "Ещё на острове",
  "session.end": "Ушёл с острова",
  "world.open": "Открыл луг",
  "world.pick": "Выбрал сад",
  "worlds.open": "Выбор сада",
  "worlds.leave": "Вернулся к садам",
  "creature.view": "Открыл зверя",
  "creature.add": "Нарисовал зверя",
  "creature.remove": "Убрал зверя",
  "creature.feed": "Покормил",
  "creature.walk": "Погулял",
  "creature.wash": "Помыл",
  "shop.open": "Открыл магазин",
  "shop.view": "Показал витрину пакетов",
  "shop.pick": "Выбрал пакет",
  "shop.pay": "Перешёл к оплате",
  "shop.checkout": "Создал счёт",
  "shop.checkout_fail": "Счёт не открылся",
  "shop.paid": "Оплатил",
  "shop.pay_fail": "Оплата не прошла",
  "shop.quote": "Посчитал цену",
  "shop.quote_fail": "Промокод не подошёл",
  "shop.topup": "Нажал пополнить",
  "shop.world_open": "Купить остров",
  "auth.otp_sent": "Запросил код",
  "auth.otp_ok": "Вошёл по коду",
  "auth.otp_fail": "Код не подошёл",
  "auth.login": "Вошёл",
  "auth.login_fail": "Не вошёл",
  "auth.register": "Зарегистрировался",
  "draw.block": "Не смог нарисовать",
  "draw.fail": "Рисунок не приняли",
  "pay.result": "Проверка оплаты",
  "cta.play": "Нажал играть",
  "cta.pricing": "Открыл цены",
  "cta.auth": "Открыл вход",
  "draw.open": "Открыл рисовалку",
  "draw.preview": "Смотрел превью",
  "photo.open": "Открыл фото рисунка",
  "roster.open": "Открыл альбом",
  "roster.guest": "Смотрел чужих зуфиков",
  "roster.select": "Выбрал зверя в альбоме",
  "vitrine.open": "Открыл витрину",
  "vitrine.search": "Искал сад",
  "vitrine.filter": "Фильтр витрины",
  "vitrine.open_zoo": "Зашёл в сад с витрины",
  "vitrine.close": "Закрыл витрину",
  "visit.open": "В гостях",
  "visit.share": "Поделился садом",
  "visit.heart": "Поставил сердце",
  "visit.close": "Вышел из гостей",
  "first_draw.offer": "Предложили нарисовать",
  "first_draw.draw": "Нарисовать с первого экрана",
  "first_draw.close": "Закрыл первое рисование",
  "auth.logout": "Вышел",
  "parent.gate": "Прошёл родительский затвор",
  "friend.invite": "Пригласили друга",
  "friend.draw": "Рисует друга",
  "friend.pay_sheet": "Магазин ради друга",
  "friend.decline": "Не купил друга",
  "friend.resume": "Вернулся к другу",
  "arcade.start": "Начал аркаду",
  "arcade.step": "Шаг аркады",
  "arcade.done": "Прошёл аркаду",
  "arcade.skip": "Пропустил аркаду",
  "diy.build": "Строит сад",
  "zoo.overview": "Весь зоопарк",
  "hud.actions": "Открыл действия",
  "page.view": "Открыл страницу",
  "play.open": "Нажал «играть» на сайте",
};

export function eventLabel(event: string) {
  return LABELS[event] || event;
}
